### ISSUE TITLE
Support for new actions

### ISSUE THREAD

**Issue by ugleatle** [HomeAssistant-Mods/home-assistant-miele-OLD-FORK-DO-NOT-USE#14]
1.02 Added the the following action

added: PUT action for ventilationStep (Hood)

I have a ventilation hood registered with the extension, and this doesn't seem to be supported. This would be great to have supported in the extension. Please let me know if I can support the implementation of this in anyway.

**Comment by kloknibor** [comment]
Hi!

Actually adding functionality like this is pretty easy. You can see an example in this commit : 0d3fec4662bdcd7431476e62e4e0c5ea1b723463 which added some functionality. And here the API details can be found : https://www.miele.com/developer/capabilities.html If you want to contribute it would be greatly appriated by making a PR. If you want ofcourse. If it is too difficult I can try to take a shot next month, but I don't have a hood to test. So that makes it guessing,

**Comment by kloknibor** [comment]
Because of a recent change in the structure of the git repo this repo has been renamed and will be no longer active. When you still require support with your question/issue please open a new issue at : https://github.com/HomeAssistant-Mods/home-assistant-miele
